language: java
install:
- mvn clean package
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: Recap-Harvester
  env: nightly-recap-harvester-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: recap-harvester-production
  on:
    repo: NYPL/recap-harvester
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: Recap-Harvester
  env: nightly-recap-harvester-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: recap-harvester-qa
  on:
    repo: NYPL/recap-harvester
    branch: qa
env:
  global:
    - secure: gATCft6WIwLznRVTyu5r6SlxArYcWpRqLvyIwrsmcf4sEtc6WO7zIj4iDVZ75ODj9Umg2jfGUOPkQbyrX4lQIsug0OxPEzBebjrusTeJCinjPU2lk2AY4ALQvnlj2luifNueuV9noZ0nj90OdHQjZrQgUehFOPN7xR6RKLlll0R/O5+m/cayVXxCPFmojdvJNtGegvoC6i9mzzKnr949XGj2F7bODa1qq5AggJJxy/6nb6YwQp9fX8p4XZcmuRKz97XGLXfo9VpqQd7SVcwqYqot+35wpo2VlXhS5Uct001G+LV++Zn/mt+mOzyo7lB0WoSuXaHevyFzdrswjYOSIuBBFnYnLa2KHCDbGfzcp1+iHRzlFec3m1+1WG92gwvBsqvjat21f/gjebkrhXsogtYlubf2YjR5dlFBG5o6zKN8MklQIOFa/xsKwcTi0S511eW+GeBgIvyOMNlbtrTaqZcTAkqD0xxgsB+wzc0a77fKDCCZTm+yq8p1S80zhp+nUJN70JVwpwis3y7kWEQalZwy8FyOVZCzIUc1e+8SetV22U0aSxhNuR/aCn/F90Mw94i9NUF+IxsadT15ZwkCt96sDo0a0hInILGx679kE3CfOEYvodCoQbOOBR4BOWQ9Xxygl90poMifAGx8mNuLV9aaJB3SVdaoWSNLtRbblSk=