language: java
install:
- mvn clean package
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: Recap-Harvester
  env: nightly-recap-harvester-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: recap-harvester-production
  on:
    repo: NYPL/recap-harvester
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: Recap-Harvester
  env: nightly-recap-harvester-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: recap-harvester-qa
  on:
    repo: NYPL/recap-harvester
    branch: qa
env:
  global:
    secure: G6uB+bUetTXcyJrr59Oz/g1ERDKC8uHgTFpf6ycGoJdsPAYbQnlGhMNv52zsrJHf9TiXzedUlVWnrIavzm2aMryRWMHiNcT08oocwTzS9TByZWoCHQxdlH8BY6ApXGA1zn9RCYCeM/1/VtNxe0QsJEduUOg0jHCnluJJWvcj354pK5DFDOs1+RBpq69qn68tfb6rVnSwz41adAsK7rQtnpREY3cJsO8F/q6XiKz+gdUMrokWVtMlVHFJksqElJo20IlZw1yiDNoJ+RAV9oo9H50drkHuTXs55gEvw5oIkOrnWbGhCampiU3edOm0azjVVXbZ9nQdGLV7CnZD0iwur4rfKthfaZry9bUSazZf2ARkGefNbbLyMku8oU0nut5m7wND2t+RhgdiU4vFpZGTrTq5A6QWUOquZAP8loJuT+zEa5tWxael7PxqUZot6EkrE/PW+ht/GKHVyu/WbyrtWsmYopmV9JKY3eCj+jLcpm+g1F2iPtQo49q0BtVQIN2JgzQSHmRzJj2QflqYm6AbjDtuaaWLcdFmYcgK2k11F3/IGIxwLhn78bvhcchbgkATjxbEEGoFXrnLziOWw8SmuJ5u6KiJUZ8lOzYg+k12l1iE9GN9wFfenOW8onfzw9mddUHFRDVNXpSjkzGdo4FgGZ/SOSR1ew0JPbGaIlCZ0a8=
