/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("org.springframework.boot") version "3.4.5"
    id("io.spring.dependency-management") version "1.1.7"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter)
    implementation(libs.org.apache.camel.camel.spring.boot.starter)
    implementation(libs.org.apache.camel.camel.jaxb)
    implementation(libs.org.apache.camel.camel.ftp)
    implementation(libs.org.apache.camel.camel.zipfile)
    implementation(libs.commons.io.commons.io)
    implementation(libs.com.fasterxml.jackson.core.jackson.databind)
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.security.oauth.spring.security.oauth2)
    implementation(libs.org.apache.camel.camel.aws)
    implementation(libs.org.apache.camel.camel.http)
    implementation(libs.org.apache.camel.camel.test)
    implementation(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.avro)
    implementation(libs.org.mockito.mockito.core)
    implementation(libs.com.google.guava.guava)
    implementation(libs.org.springframework.retry.spring.retry)
    implementation(libs.javax.xml.bind.jaxb.api)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.com.github.stefanbirkner.system.rules)
}


group = "com.recap"
version = "0.0.1-SNAPSHOT"
description = "harvester"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
